services:
  app:
    build: .
    container_name: task-tracker-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/tasktracker
    depends_on:
      - mongo
    networks:
      - task-network

  mongo:
    image: mongo:7
    container_name: task-tracker-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - task-network

networks:
  task-network:

volumes:
  mongo-data:

